databases:
  - name: ndmsk-db
    databaseName: ndmsk
    user: ndmsk_user
    plan: free

services:
  - type: web
    name: ndmsk-technology
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ndmsk-db
          property: connectionString
      - key: NODE_ENV
        value: production
